command_timeout = 1000

[aws]
format = ""

[directory]
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch]($style) "

[nodejs]
disabled = true

[line_break]
disabled = false

[time]
disabled = false
format = 'ğŸ•™[ $time ]($style)'
time_format = "%R"

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡¡${ahead_count} â‡£${behind_count}"
behind = "â‡£${count}"
conflicted = "[ğŸ¤ª${count}](bright-red) "
untracked = "ğŸ¤·â€${count} "
stashed = "[ğŸ“¦ ${count}](bright-blue) "
modified = "[ğŸ“’${count}](yellow) "
staged = "[âœ”${count}](green) "
renamed = "[ğŸš—${count}](bright-red) "
deleted = "[ğŸ—‘${count}](red) "

[git_commit]
only_detached = false

[java]
disabled = true

[package]
disabled = true
